POST http://localhost:8080/animals
Content-Type: application/json
Authorization: Basic username password

{
  "id": "ssss2222",
  "name": "panda",
  "originCountry": "japan"
}

###

GET http://localhost:8080/animals
Content-Type: application/json
Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=
#Authorization: Basic username password

###

PUT http://localhost:8080/animals/jjjj33
Content-Type: application/json

{
  "id": "jjjj33",
  "name": "panda",
  "originCountry": "japan"
}

###

GET http://localhost:8080/animals/countries/j
Content-Type: application/json
Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=